# Generated by Django 4.2 on 2023-06-27 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crypto_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parser",
            name="One_hour",
            field=models.DecimalField(decimal_places=6, max_digits=8),
        ),
        migrations.AlterField(
            model_name="parser",
            name="Price",
            field=models.DecimalField(decimal_places=8, max_digits=10),
        ),
        migrations.AlterField(
            model_name="parser",
            name="seven_days",
            field=models.DecimalField(decimal_places=6, max_digits=8),
        ),
        migrations.AlterField(
            model_name="parser",
            name="twenty_four_hours",
            field=models.DecimalField(decimal_places=6, max_digits=8),
        ),
    ]
